# This is a basic workflow to help you get started with Actions

name: build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v1.2.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Run the build
      run: |
        make install
        make test
      
  pypi:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v1.2.0
      with:
        python-version: 3.7
    - name: Create pypi dist
      run: make dist
    - name: pypi-publish
      uses: pypa/gh-action-pypi-publish@v1.1.0
      env:
        pypi_token: ${{ secrets.pypi }}
      with:
        password: ${{ secrets.SuperSecret }}
    
